languageCode = "en"
languageName = "English"
weight = 1
title = "comfylang"
contentDir = "content/en"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "comfylang"
dateFormat = "2 January 2006"
logo = "white.jpg"

  [params.author]
  name = "Gray Blowfish"
  image = "img/avatar.png"
  headline = "This is my very simple profile website with my links"
  bio = "A little bit about you"
  links = [ ]

["params.author"]
image = "comfy-icon.png"
name = "comfylang"
headline = "A low-level scripting language for fast arm32 development"
