[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "GitHub"
pre = "github"
url = "https://github.com/comfy-lang/"
identifier = "2n0SSnJjed"
weight = 9_999

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10
